services:
  service-a:
    build: ./services/service-a
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=service-a
      - PORT=8080
    networks:
      - app-network
    depends_on:
      - otel-collector
      - service-b

  service-b:
    build: ./services/service-b
    restart: always
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=service-b
      - PORT=8081
    networks:
      - app-network
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - app-network
    depends_on:
      - zipkin
    ports:
      - "4318:4318"   # HTTP OTLP
      - "4317:4317"   # gRPC OTLP
      - "8888:8888"   # métricas

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
